apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-0                  
  labels:
    app: mysql
    index: "0"
spec:
  capacity:
    storage: 5Gi            
  accessModes:
    - ReadWriteOnce           
  persistentVolumeReclaimPolicy: Retain   
  storageClassName: ""              
  hostPath:
    path: /data/mysql/pv-0            
    type: DirectoryOrCreate           

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-1          
  labels:
    app: mysql
    index: "1"
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""                
  hostPath:
    path: /data/mysql/pv-1
    type: DirectoryOrCreate   

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-2                
  labels:
    app: mysql
    index: "2"
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:    
    path: /data/mysql/pv-2
    type: DirectoryOrCreate           
