apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: mysql-demo
data:
  # PRIMARY Configuration (applied when pod index = 0)
  primary.cnf: |
    [mysqld]
    log-bin=mysql-bin
    binlog-format=ROW
    gtid-mode=ON
    enforce-gtid-consistency=ON
    log-slave-updates=ON

  # REPLICA Configuration (applied when pod index > 0
  replica.cnf: |
    [mysqld]
    super-read-only=ON
    log-bin=mysql-bin
    binlog-format=ROW
    gtid-mode=ON
    enforce-gtid-consistency=ON
    log-slave-updates=ON
