apiVersion: v1
kind: Service
metadata:
  name: mysql-headless
  namespace: mysql-demo
  labels:
    app: mysql
spec:
  clusterIP: None                 
  selector:
    app: mysql
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
    - name: xtrabackup
      port: 3307
      targetPort: 3307
