apiVersion: v1
kind: Pod
metadata:
  name: persistent-pod
spec:
  containers:
  - name: persistentcon
    image: busybox
    command: ["sleep", "3600"]
    volumeMounts:
    - mountPath: /pv/data
      name: pvc-storage
  volumes:
  - name: pvc-storage
    persistentVolumeClaim:
      claimName: demo-pvc
