apiVersion: v1
kind: Pod
metadata:
  name: forced-pod
spec:
  nodeSelector:
    kubernetes.io/hostname: ip-172-31-71-223
  containers:
  - name: nginx
    image: nginx
  tolerations:
  - key: "dev"
    operator: "Equal"
    value: "true"
    effect: "NoSchedule"
