apiVersion: v1
kind: Pod
metadata:
  name: affinity-req-notlabeled
  namespace: nodeaff
spec:
  containers:
  - name: nginx
    image: nginx
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: env
            operator: In
            values:
            - staging
