apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      name: registry-pod
      labels:
        app: registry
    spec: 
      containers:
      - name: registrycon
        image: vinaykumarkondoju08/meridian-registry-service:latest
        ports:
        - containerPort: 8761
        env:
        - name: PORT
          value: "8761"
        - name: REGISTRY_TTL_MS
          value: "90000"

