apiVersion: apps/v1
kind: Deployment
metadata: 
  name: config-secret-pod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: configsecretapp
  template:
    metadata:
      name: configsecret
      labels:
        app: configsecretapp
    spec:
      containers:
      - name: configsecretcon
        image: vinaykumarkondoju08/spring-application:01
        ports:
        - containerPort: 8080
        env:
        - name: APP_NAME
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: APP_NAME
        - name: ENVIRONMENT
          valueFrom: 
            configMapKeyRef:
              name: app-config
              key: ENVIRONMENT
        - name: APP_MESSAGE
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: APP_MESSAGE
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: DB_PASSWORD


